# Generated by Django 4.1.3 on 2023-07-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_prices', '0002_remove_cryptoprice_timestamp_alter_cryptoprice_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoprice',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
