# Generated by Django 4.1.3 on 2023-07-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_prices', '0003_alter_cryptoprice_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoprice',
            name='symbol',
            field=models.CharField(max_length=100),
        ),
    ]
