# Generated by Django 4.1.3 on 2023-07-05 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_prices', '0004_alter_cryptoprice_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoprice',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cryptoprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cryptoprice',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
