# Generated by Django 4.1.3 on 2023-07-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_prices', '0006_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
