# Generated by Django 4.1.3 on 2023-07-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_prices', '0007_purchase_amount_usd_alter_purchase_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='amount_usd',
        ),
    ]
